=== dasha-kovalenko/UniversityProjects1/footXML/Match.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.clientmatch.by.kdv/Match" xmlns:tns="http://www.clientmatch.by.kdv/Match" elementFormDefault="qualified">

    <complexType name="Match">
    	<sequence>
    		<element name="id" type="int"></element>
    		<element name="team1" type="string"></element>
    		<element name="team2" type="string"></element>
    		<element name="count" type="string"></element>
    		<element name="matchdate" type="date"></element>

    	</sequence>
    </complexType>

    <complexType name="MatchList">
    	<sequence>
            <element name="temp" type="string"></element>
            <element name="match" type="tns:Match"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>
    
    <element name="MatchList" type="tns:MatchList"></element>
</schema>

=== dasha-kovalenko/UniversityProjects1/footXML/Match.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:MatchList xmlns:tns="http://www.clientmatch.by.kdv/Match" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.clientmatch.by.kdv/Match Match.xsd ">
  <tns:temp>temp</tns:temp>
  <tns:match>
    <tns:id>0</tns:id>
    <tns:team1>arsenal</tns:team1>
    <tns:team2>manchester-united</tns:team2>
    <tns:count>1:2</tns:count>
    <tns:matchdate>2012-01-22</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>2</tns:id>
    <tns:team1>sunderland</tns:team1>
    <tns:team2>arsenal</tns:team2>
    <tns:count>1:2</tns:count>
    <tns:matchdate>2012-02-11</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>3</tns:id>
    <tns:team1>barselona</tns:team1>
    <tns:team2>liverpool</tns:team2>
    <tns:count>3:1</tns:count>
    <tns:matchdate>2012-03-02</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>4</tns:id>
    <tns:team1>arsenal</tns:team1>
    <tns:team2>barselona</tns:team2>
    <tns:count>1:1</tns:count>
    <tns:matchdate>2012-01-01</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>5</tns:id>
    <tns:team1>tottenham</tns:team1>
    <tns:team2>manchester-united</tns:team2>
    <tns:count>1:3</tns:count>
    <tns:matchdate>2012-03-04</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>6</tns:id>
    <tns:team1>chelsea</tns:team1>
    <tns:team2>burmingham</tns:team2>
    <tns:count>2:0</tns:count>
    <tns:matchdate>2012-03-06</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>11</tns:id>
    <tns:team1>sunderland</tns:team1>
    <tns:team2>tottenham</tns:team2>
    <tns:count>5:1</tns:count>
    <tns:matchdate>2012-04-02</tns:matchdate>
  </tns:match>
  <tns:match>
    <tns:id>12</tns:id>
    <tns:team1>barselona</tns:team1>
    <tns:team2>manchester-united</tns:team2>
    <tns:count>3:1</tns:count>
    <tns:matchdate>2012-04-03</tns:matchdate>
  </tns:match>
</tns:MatchList>
