=== dasha-kovalenko/UniversityProjects1/!Done/lab4/Candidate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.clientcandidate.aig.by/Candidate" xmlns:tns="http://www.clientcandidate.aig.by/Candidate" elementFormDefault="qualified">

    <complexType name="Candidate">
    	<sequence>
    		<element name="id" type="int"></element>
    		<element name="age" type="int"></element>
    		<element name="name" type="string"></element>
    		<element name="male" type="boolean"></element>
    		<element name="country" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="city" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="phone" type="string"></element>
    	</sequence>
    </complexType>
    

    <complexType name="CandidateList">
    	<sequence>
            <element name="temp" type="string"></element>
            <element name="candidate" type="tns:Candidate"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>
    
    <element name="CandidateList" type="tns:CandidateList"></element>
</schema>

=== dasha-kovalenko/UniversityProjects1/!Done/lab4/Candidate.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:CandidateList xmlns:tns="http://www.clientcandidate.aig.by/Candidate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.clientcandidate.aig.by/Candidate Candidate.xsd ">
  <tns:temp>temp</tns:temp>
  <tns:candidate>
    <tns:id>0</tns:id>
    <tns:age>21</tns:age>
    <tns:name>asd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>123</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>2</tns:id>
    <tns:age>21</tns:age>
    <tns:name>asd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>123</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>5</tns:id>
    <tns:age>21</tns:age>
    <tns:name>jhbbljkljkl</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>1234</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>6</tns:id>
    <tns:age>21</tns:age>
    <tns:name>кпвап</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>123</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>7</tns:id>
    <tns:age>21</tns:age>
    <tns:name>ыапв</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>123</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>8</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>9</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>10</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>11</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>12</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>13</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>14</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>15</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>16</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>17</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>18</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>19</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>20</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>21</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>22</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>23</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>24</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>25</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>26</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>27</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>28</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>29</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>30</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>31</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>32</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>33</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>34</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>35</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>36</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>37</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>38</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>39</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>40</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>41</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>42</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>43</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>44</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>45</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>46</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>47</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>48</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>49</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>50</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>51</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>52</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
    <tns:phone>2112121212</tns:phone>
  </tns:candidate>
  <tns:candidate>
    <tns:id>53</tns:id>
    <tns:age>21</tns:age>
    <tns:name>dssd</tns:name>
    <tns:male>true</tns:male>
