=== dasha-kovalenko/UniversityProjects1/Airline/Airline/build/classes/xml/planes.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">      
    <xs:complexType name="passenger">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="capacity" type="xs:int"/>
            <xs:element name="speed" type="xs:int"/>
            <xs:element name="tonnage" type="xs:int"/>
            <xs:element name="distance" type="xs:int"/>
            <xs:element name="price" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>  
    <xs:complexType name="freight">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="capacity" type="xs:int"/>
            <xs:element name="speed" type="xs:int"/>
            <xs:element name="tonnage" type="xs:int"/>
            <xs:element name="distance" type="xs:int"/>
            <xs:element name="freightType" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>   
    <xs:complexType name="military">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="capacity" type="xs:int"/>
            <xs:element name="speed" type="xs:int"/>
            <xs:element name="tonnage" type="xs:int"/>
            <xs:element name="distance" type="xs:int"/>
            <xs:element name="calibreWeight" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>    
    <xs:complexType name="planes">
        <xs:sequence>
            <xs:element name="passenger" type="passenger" maxOccurs="10"/>
            <xs:element name="military" type="military" maxOccurs="10"/>
            <xs:element name="freight" type="freight" maxOccurs="10"/>
        </xs:sequence>
    </xs:complexType>   
    <xs:element name="planes" type = "planes"/>  
</xs:schema>

=== dasha-kovalenko/UniversityProjects1/Airline/Airline/src/xml/airlinep.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<planes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='null'
    xsi:noNamespaceSchemaLocation='planes.xsd'>
      <passenger>
          <name>TY</name>
          <capacity>230</capacity>
          <speed>1400</speed>
          <tonnage>1600</tonnage>
          <distance>3400</distance>
          <price>700</price>
      </passenger>
      <military>
          <name>Boeing</name>
          <capacity>230</capacity>
          <speed>1400</speed>
          <tonnage>1600</tonnage>
          <distance>3400</distance>
          <calibreWeight>340</calibreWeight>
      </military>  
      <freight>
          <name>Yak</name>
          <capacity>230</capacity>
          <speed>1400</speed>
          <tonnage>1600</tonnage>
          <distance>3400</distance>
          <freightType>products</freightType>
      </freight>   
</planes>
