=== dasha-kovalenko/UniversityProjects1/TransportXML/TrXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/TrXMLSchema" xmlns:tns="http://www.example.org/TrXMLSchema" elementFormDefault="qualified">

    <element name="ListOfTransports" type="tns:List"></element>
    
    <complexType name="List">
    	<sequence>
            <element name="Bus" type="tns:BusType" maxOccurs="unbounded" minOccurs="0"></element>
            <element name="Trolleybus" type="tns:TrolleybusType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="BusType">
    	<complexContent>
    		<extension base="tns:TransportType">
    			<sequence>
    				<element name="amountOfFuel" type="int"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="TrolleybusType">
    	<complexContent>
    		<extension base="tns:TransportType">
    			<sequence>
    				<element name="energy" type="int"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="TransportType">
    	<sequence>
    		<element name="number" type="int"></element>
    		<element name="start" type="time"></element>
    		<element name="finish" type="time"></element>
    		<element name="route" type="string"></element>
    		<element name="price" type="int"></element>
    		<element name="interval" type="int"></element>
    		<element name="capacity" type="int"></element>
    	</sequence>
    </complexType>
</schema>

=== dasha-kovalenko/UniversityProjects1/TransportXML/TransportXML/TrXMLSchema3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ListOfTransports xmlns:tns="http://www.example.org/TrXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/TrXMLSchema TrXMLSchema.xsd ">
  <tns:Bus>
    <tns:number>2</tns:number>
    <tns:start>05:30:00</tns:start>
    <tns:finish>00:10:00</tns:finish>
    <tns:route>A-B</tns:route>
    <tns:price>100</tns:price>
    <tns:interval>5</tns:interval>
    <tns:capacity>66</tns:capacity>
    <tns:amountOfFuel>150</tns:amountOfFuel>
  </tns:Bus>
  <tns:Trolleybus>
    <tns:number>78</tns:number>
    <tns:start>06:05:00</tns:start>
    <tns:finish>01:20:00</tns:finish>
    <tns:route>A-K-L-B-C-C</tns:route>
    <tns:price>50</tns:price>
    <tns:interval>5</tns:interval>
    <tns:capacity>100</tns:capacity>
    <tns:energy>1550</tns:energy>
  </tns:Trolleybus>
</tns:ListOfTransports>
